// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.2
//   protoc               v6.32.1
// source: message.proto

/* eslint-disable */
import * as _m0 from "protobufjs/minimal";

export const protobufPackage = "proto.autobahn";

export enum MessageType {
  SERVER_STATE = 0,
  SERVER_FORWARD = 1,
  PUBLISH = 2,
  SUBSCRIBE = 3,
  UNSUBSCRIBE = 4,
  UNRECOGNIZED = -1,
}

export function messageTypeFromJSON(object: any): MessageType {
  switch (object) {
    case 0:
    case "SERVER_STATE":
      return MessageType.SERVER_STATE;
    case 1:
    case "SERVER_FORWARD":
      return MessageType.SERVER_FORWARD;
    case 2:
    case "PUBLISH":
      return MessageType.PUBLISH;
    case 3:
    case "SUBSCRIBE":
      return MessageType.SUBSCRIBE;
    case 4:
    case "UNSUBSCRIBE":
      return MessageType.UNSUBSCRIBE;
    case -1:
    case "UNRECOGNIZED":
    default:
      return MessageType.UNRECOGNIZED;
  }
}

export function messageTypeToJSON(object: MessageType): string {
  switch (object) {
    case MessageType.SERVER_STATE:
      return "SERVER_STATE";
    case MessageType.SERVER_FORWARD:
      return "SERVER_FORWARD";
    case MessageType.PUBLISH:
      return "PUBLISH";
    case MessageType.SUBSCRIBE:
      return "SUBSCRIBE";
    case MessageType.UNSUBSCRIBE:
      return "UNSUBSCRIBE";
    case MessageType.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export enum RPCMessageType {
  RPC_REQUEST = 0,
  RPC_RESPONSE = 1,
  UNRECOGNIZED = -1,
}

export function rPCMessageTypeFromJSON(object: any): RPCMessageType {
  switch (object) {
    case 0:
    case "RPC_REQUEST":
      return RPCMessageType.RPC_REQUEST;
    case 1:
    case "RPC_RESPONSE":
      return RPCMessageType.RPC_RESPONSE;
    case -1:
    case "UNRECOGNIZED":
    default:
      return RPCMessageType.UNRECOGNIZED;
  }
}

export function rPCMessageTypeToJSON(object: RPCMessageType): string {
  switch (object) {
    case RPCMessageType.RPC_REQUEST:
      return "RPC_REQUEST";
    case RPCMessageType.RPC_RESPONSE:
      return "RPC_RESPONSE";
    case RPCMessageType.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export enum RPCResponseType {
  RPC_RESPONSE_SUCCESS = 0,
  RPC_RESPONSE_ERROR = 1,
  UNRECOGNIZED = -1,
}

export function rPCResponseTypeFromJSON(object: any): RPCResponseType {
  switch (object) {
    case 0:
    case "RPC_RESPONSE_SUCCESS":
      return RPCResponseType.RPC_RESPONSE_SUCCESS;
    case 1:
    case "RPC_RESPONSE_ERROR":
      return RPCResponseType.RPC_RESPONSE_ERROR;
    case -1:
    case "UNRECOGNIZED":
    default:
      return RPCResponseType.UNRECOGNIZED;
  }
}

export function rPCResponseTypeToJSON(object: RPCResponseType): string {
  switch (object) {
    case RPCResponseType.RPC_RESPONSE_SUCCESS:
      return "RPC_RESPONSE_SUCCESS";
    case RPCResponseType.RPC_RESPONSE_ERROR:
      return "RPC_RESPONSE_ERROR";
    case RPCResponseType.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export interface AbstractMessage {
  messageType: MessageType;
}

export interface ServerStateMessage {
  messageType: MessageType;
  uuid: string;
  topics: string[];
}

export interface ServerForwardMessage {
  messageType: MessageType;
  payload: Uint8Array;
}

export interface TopicMessage {
  messageType: MessageType;
  topic: string;
}

export interface PublishMessage {
  messageType: MessageType;
  topic: string;
  payload: Uint8Array;
}

export interface UnsubscribeMessage {
  messageType: MessageType;
  topic: string;
}

export interface RPCMessage {
  messageType: RPCMessageType;
  callId: string;
}

export interface RPCRequestMessage {
  messageType: RPCMessageType;
  callId: string;
  payload: Uint8Array;
}

export interface RPCResponseMessage {
  messageType: RPCMessageType;
  callId: string;
  responseType: RPCResponseType;
  payload: Uint8Array;
}

export interface RPCEmpty {
}

function createBaseAbstractMessage(): AbstractMessage {
  return { messageType: 0 };
}

export const AbstractMessage = {
  encode(message: AbstractMessage, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.messageType !== 0) {
      writer.uint32(8).int32(message.messageType);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): AbstractMessage {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAbstractMessage();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.messageType = reader.int32() as any;
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): AbstractMessage {
    return { messageType: isSet(object.messageType) ? messageTypeFromJSON(object.messageType) : 0 };
  },

  toJSON(message: AbstractMessage): unknown {
    const obj: any = {};
    if (message.messageType !== 0) {
      obj.messageType = messageTypeToJSON(message.messageType);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<AbstractMessage>, I>>(base?: I): AbstractMessage {
    return AbstractMessage.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<AbstractMessage>, I>>(object: I): AbstractMessage {
    const message = createBaseAbstractMessage();
    message.messageType = object.messageType ?? 0;
    return message;
  },
};

function createBaseServerStateMessage(): ServerStateMessage {
  return { messageType: 0, uuid: "", topics: [] };
}

export const ServerStateMessage = {
  encode(message: ServerStateMessage, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.messageType !== 0) {
      writer.uint32(8).int32(message.messageType);
    }
    if (message.uuid !== "") {
      writer.uint32(18).string(message.uuid);
    }
    for (const v of message.topics) {
      writer.uint32(26).string(v!);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): ServerStateMessage {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseServerStateMessage();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.messageType = reader.int32() as any;
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.uuid = reader.string();
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.topics.push(reader.string());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ServerStateMessage {
    return {
      messageType: isSet(object.messageType) ? messageTypeFromJSON(object.messageType) : 0,
      uuid: isSet(object.uuid) ? globalThis.String(object.uuid) : "",
      topics: globalThis.Array.isArray(object?.topics) ? object.topics.map((e: any) => globalThis.String(e)) : [],
    };
  },

  toJSON(message: ServerStateMessage): unknown {
    const obj: any = {};
    if (message.messageType !== 0) {
      obj.messageType = messageTypeToJSON(message.messageType);
    }
    if (message.uuid !== "") {
      obj.uuid = message.uuid;
    }
    if (message.topics?.length) {
      obj.topics = message.topics;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ServerStateMessage>, I>>(base?: I): ServerStateMessage {
    return ServerStateMessage.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ServerStateMessage>, I>>(object: I): ServerStateMessage {
    const message = createBaseServerStateMessage();
    message.messageType = object.messageType ?? 0;
    message.uuid = object.uuid ?? "";
    message.topics = object.topics?.map((e) => e) || [];
    return message;
  },
};

function createBaseServerForwardMessage(): ServerForwardMessage {
  return { messageType: 0, payload: new Uint8Array(0) };
}

export const ServerForwardMessage = {
  encode(message: ServerForwardMessage, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.messageType !== 0) {
      writer.uint32(8).int32(message.messageType);
    }
    if (message.payload.length !== 0) {
      writer.uint32(18).bytes(message.payload);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): ServerForwardMessage {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseServerForwardMessage();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.messageType = reader.int32() as any;
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.payload = reader.bytes();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ServerForwardMessage {
    return {
      messageType: isSet(object.messageType) ? messageTypeFromJSON(object.messageType) : 0,
      payload: isSet(object.payload) ? bytesFromBase64(object.payload) : new Uint8Array(0),
    };
  },

  toJSON(message: ServerForwardMessage): unknown {
    const obj: any = {};
    if (message.messageType !== 0) {
      obj.messageType = messageTypeToJSON(message.messageType);
    }
    if (message.payload.length !== 0) {
      obj.payload = base64FromBytes(message.payload);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ServerForwardMessage>, I>>(base?: I): ServerForwardMessage {
    return ServerForwardMessage.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ServerForwardMessage>, I>>(object: I): ServerForwardMessage {
    const message = createBaseServerForwardMessage();
    message.messageType = object.messageType ?? 0;
    message.payload = object.payload ?? new Uint8Array(0);
    return message;
  },
};

function createBaseTopicMessage(): TopicMessage {
  return { messageType: 0, topic: "" };
}

export const TopicMessage = {
  encode(message: TopicMessage, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.messageType !== 0) {
      writer.uint32(8).int32(message.messageType);
    }
    if (message.topic !== "") {
      writer.uint32(18).string(message.topic);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): TopicMessage {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTopicMessage();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.messageType = reader.int32() as any;
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.topic = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): TopicMessage {
    return {
      messageType: isSet(object.messageType) ? messageTypeFromJSON(object.messageType) : 0,
      topic: isSet(object.topic) ? globalThis.String(object.topic) : "",
    };
  },

  toJSON(message: TopicMessage): unknown {
    const obj: any = {};
    if (message.messageType !== 0) {
      obj.messageType = messageTypeToJSON(message.messageType);
    }
    if (message.topic !== "") {
      obj.topic = message.topic;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<TopicMessage>, I>>(base?: I): TopicMessage {
    return TopicMessage.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<TopicMessage>, I>>(object: I): TopicMessage {
    const message = createBaseTopicMessage();
    message.messageType = object.messageType ?? 0;
    message.topic = object.topic ?? "";
    return message;
  },
};

function createBasePublishMessage(): PublishMessage {
  return { messageType: 0, topic: "", payload: new Uint8Array(0) };
}

export const PublishMessage = {
  encode(message: PublishMessage, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.messageType !== 0) {
      writer.uint32(8).int32(message.messageType);
    }
    if (message.topic !== "") {
      writer.uint32(18).string(message.topic);
    }
    if (message.payload.length !== 0) {
      writer.uint32(26).bytes(message.payload);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): PublishMessage {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePublishMessage();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.messageType = reader.int32() as any;
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.topic = reader.string();
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.payload = reader.bytes();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): PublishMessage {
    return {
      messageType: isSet(object.messageType) ? messageTypeFromJSON(object.messageType) : 0,
      topic: isSet(object.topic) ? globalThis.String(object.topic) : "",
      payload: isSet(object.payload) ? bytesFromBase64(object.payload) : new Uint8Array(0),
    };
  },

  toJSON(message: PublishMessage): unknown {
    const obj: any = {};
    if (message.messageType !== 0) {
      obj.messageType = messageTypeToJSON(message.messageType);
    }
    if (message.topic !== "") {
      obj.topic = message.topic;
    }
    if (message.payload.length !== 0) {
      obj.payload = base64FromBytes(message.payload);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<PublishMessage>, I>>(base?: I): PublishMessage {
    return PublishMessage.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<PublishMessage>, I>>(object: I): PublishMessage {
    const message = createBasePublishMessage();
    message.messageType = object.messageType ?? 0;
    message.topic = object.topic ?? "";
    message.payload = object.payload ?? new Uint8Array(0);
    return message;
  },
};

function createBaseUnsubscribeMessage(): UnsubscribeMessage {
  return { messageType: 0, topic: "" };
}

export const UnsubscribeMessage = {
  encode(message: UnsubscribeMessage, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.messageType !== 0) {
      writer.uint32(8).int32(message.messageType);
    }
    if (message.topic !== "") {
      writer.uint32(18).string(message.topic);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): UnsubscribeMessage {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUnsubscribeMessage();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.messageType = reader.int32() as any;
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.topic = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UnsubscribeMessage {
    return {
      messageType: isSet(object.messageType) ? messageTypeFromJSON(object.messageType) : 0,
      topic: isSet(object.topic) ? globalThis.String(object.topic) : "",
    };
  },

  toJSON(message: UnsubscribeMessage): unknown {
    const obj: any = {};
    if (message.messageType !== 0) {
      obj.messageType = messageTypeToJSON(message.messageType);
    }
    if (message.topic !== "") {
      obj.topic = message.topic;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<UnsubscribeMessage>, I>>(base?: I): UnsubscribeMessage {
    return UnsubscribeMessage.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UnsubscribeMessage>, I>>(object: I): UnsubscribeMessage {
    const message = createBaseUnsubscribeMessage();
    message.messageType = object.messageType ?? 0;
    message.topic = object.topic ?? "";
    return message;
  },
};

function createBaseRPCMessage(): RPCMessage {
  return { messageType: 0, callId: "" };
}

export const RPCMessage = {
  encode(message: RPCMessage, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.messageType !== 0) {
      writer.uint32(8).int32(message.messageType);
    }
    if (message.callId !== "") {
      writer.uint32(18).string(message.callId);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): RPCMessage {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRPCMessage();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.messageType = reader.int32() as any;
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.callId = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): RPCMessage {
    return {
      messageType: isSet(object.messageType) ? rPCMessageTypeFromJSON(object.messageType) : 0,
      callId: isSet(object.callId) ? globalThis.String(object.callId) : "",
    };
  },

  toJSON(message: RPCMessage): unknown {
    const obj: any = {};
    if (message.messageType !== 0) {
      obj.messageType = rPCMessageTypeToJSON(message.messageType);
    }
    if (message.callId !== "") {
      obj.callId = message.callId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<RPCMessage>, I>>(base?: I): RPCMessage {
    return RPCMessage.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RPCMessage>, I>>(object: I): RPCMessage {
    const message = createBaseRPCMessage();
    message.messageType = object.messageType ?? 0;
    message.callId = object.callId ?? "";
    return message;
  },
};

function createBaseRPCRequestMessage(): RPCRequestMessage {
  return { messageType: 0, callId: "", payload: new Uint8Array(0) };
}

export const RPCRequestMessage = {
  encode(message: RPCRequestMessage, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.messageType !== 0) {
      writer.uint32(8).int32(message.messageType);
    }
    if (message.callId !== "") {
      writer.uint32(18).string(message.callId);
    }
    if (message.payload.length !== 0) {
      writer.uint32(26).bytes(message.payload);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): RPCRequestMessage {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRPCRequestMessage();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.messageType = reader.int32() as any;
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.callId = reader.string();
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.payload = reader.bytes();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): RPCRequestMessage {
    return {
      messageType: isSet(object.messageType) ? rPCMessageTypeFromJSON(object.messageType) : 0,
      callId: isSet(object.callId) ? globalThis.String(object.callId) : "",
      payload: isSet(object.payload) ? bytesFromBase64(object.payload) : new Uint8Array(0),
    };
  },

  toJSON(message: RPCRequestMessage): unknown {
    const obj: any = {};
    if (message.messageType !== 0) {
      obj.messageType = rPCMessageTypeToJSON(message.messageType);
    }
    if (message.callId !== "") {
      obj.callId = message.callId;
    }
    if (message.payload.length !== 0) {
      obj.payload = base64FromBytes(message.payload);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<RPCRequestMessage>, I>>(base?: I): RPCRequestMessage {
    return RPCRequestMessage.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RPCRequestMessage>, I>>(object: I): RPCRequestMessage {
    const message = createBaseRPCRequestMessage();
    message.messageType = object.messageType ?? 0;
    message.callId = object.callId ?? "";
    message.payload = object.payload ?? new Uint8Array(0);
    return message;
  },
};

function createBaseRPCResponseMessage(): RPCResponseMessage {
  return { messageType: 0, callId: "", responseType: 0, payload: new Uint8Array(0) };
}

export const RPCResponseMessage = {
  encode(message: RPCResponseMessage, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.messageType !== 0) {
      writer.uint32(8).int32(message.messageType);
    }
    if (message.callId !== "") {
      writer.uint32(18).string(message.callId);
    }
    if (message.responseType !== 0) {
      writer.uint32(24).int32(message.responseType);
    }
    if (message.payload.length !== 0) {
      writer.uint32(34).bytes(message.payload);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): RPCResponseMessage {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRPCResponseMessage();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.messageType = reader.int32() as any;
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.callId = reader.string();
          continue;
        case 3:
          if (tag !== 24) {
            break;
          }

          message.responseType = reader.int32() as any;
          continue;
        case 4:
          if (tag !== 34) {
            break;
          }

          message.payload = reader.bytes();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): RPCResponseMessage {
    return {
      messageType: isSet(object.messageType) ? rPCMessageTypeFromJSON(object.messageType) : 0,
      callId: isSet(object.callId) ? globalThis.String(object.callId) : "",
      responseType: isSet(object.responseType) ? rPCResponseTypeFromJSON(object.responseType) : 0,
      payload: isSet(object.payload) ? bytesFromBase64(object.payload) : new Uint8Array(0),
    };
  },

  toJSON(message: RPCResponseMessage): unknown {
    const obj: any = {};
    if (message.messageType !== 0) {
      obj.messageType = rPCMessageTypeToJSON(message.messageType);
    }
    if (message.callId !== "") {
      obj.callId = message.callId;
    }
    if (message.responseType !== 0) {
      obj.responseType = rPCResponseTypeToJSON(message.responseType);
    }
    if (message.payload.length !== 0) {
      obj.payload = base64FromBytes(message.payload);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<RPCResponseMessage>, I>>(base?: I): RPCResponseMessage {
    return RPCResponseMessage.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RPCResponseMessage>, I>>(object: I): RPCResponseMessage {
    const message = createBaseRPCResponseMessage();
    message.messageType = object.messageType ?? 0;
    message.callId = object.callId ?? "";
    message.responseType = object.responseType ?? 0;
    message.payload = object.payload ?? new Uint8Array(0);
    return message;
  },
};

function createBaseRPCEmpty(): RPCEmpty {
  return {};
}

export const RPCEmpty = {
  encode(_: RPCEmpty, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): RPCEmpty {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRPCEmpty();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): RPCEmpty {
    return {};
  },

  toJSON(_: RPCEmpty): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<RPCEmpty>, I>>(base?: I): RPCEmpty {
    return RPCEmpty.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RPCEmpty>, I>>(_: I): RPCEmpty {
    const message = createBaseRPCEmpty();
    return message;
  },
};

function bytesFromBase64(b64: string): Uint8Array {
  if ((globalThis as any).Buffer) {
    return Uint8Array.from(globalThis.Buffer.from(b64, "base64"));
  } else {
    const bin = globalThis.atob(b64);
    const arr = new Uint8Array(bin.length);
    for (let i = 0; i < bin.length; ++i) {
      arr[i] = bin.charCodeAt(i);
    }
    return arr;
  }
}

function base64FromBytes(arr: Uint8Array): string {
  if ((globalThis as any).Buffer) {
    return globalThis.Buffer.from(arr).toString("base64");
  } else {
    const bin: string[] = [];
    arr.forEach((byte) => {
      bin.push(globalThis.String.fromCharCode(byte));
    });
    return globalThis.btoa(bin.join(""));
  }
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}
